version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: codie_db
    environment:
      - POSTGRES_USER=codie
      - POSTGRES_PASSWORD=codie
      - POSTGRES_DB=codie_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # API Gateway (not fully utilized yet)
  api_gateway:
    container_name: codie-api_gateway-1
    build: ./api_gateway
    ports:
      - "8000:8000"
    env_file:
      - ./.env # Load variables from .env file
    depends_on:
      - analysis_orchestrator
      - chat_service

  # Analysis Orchestrator - The "brain"
  analysis_orchestrator:
    container_name: codie-analysis_orchestrator-1
    build: ./analysis_orchestrator
    ports:
      - "8001:8000"
    env_file:
      - ./.env # Load Snyk and other tokens from .env
    depends_on:
      - db
      - repo_analysis
      - dynamic_testing
      - style_learner
      - chat_service

  # Static code analysis service
  repo_analysis:
    container_name: codie-repo_analysis-1
    build: ./repo_analysis
    env_file:
      - ./.env

  # Dynamic testing and code coverage service
  dynamic_testing:
    container_name: codie-dynamic_testing-1
    build: ./dynamic_testing
    # Mounting docker.sock allows this service to run Docker commands
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env

  # Code style profile learner
  style_learner:
    container_name: codie-style_learner-1
    build: ./style_learner
    env_file:
      - ./.env

  # Real-time chat and AI integration service
  chat_service:
    container_name: codie-chat_service-1
    build: ./chat_service
    ports:
      - "8002:8000"
    env_file:
      - ./.env # Load Hugging Face token from .env
    depends_on:
      - db

volumes:
  postgres_data: